export const DATA_LOADED = 'DATA_LOADED';
export type DATA_LOADED = typeof DATA_LOADED;

export const SELECT_PRIORITIES = 'SELECT_PRIORITIES';
export type SELECT_PRIORITIES = typeof SELECT_PRIORITIES;

export const FILTER_PRIORITIES = 'FILTER_PRIORITIES';
export type FILTER_PRIORITIES = typeof FILTER_PRIORITIES;

export const CHANGE_PRIORITY = 'CHANGE_PRIORITY';
export type CHANGE_PRIORITY = typeof CHANGE_PRIORITY;

export enum PRIORITY_LIMITS {
  MAX_PRIORITY = 1,
  MIN_PRIORITY = 5
}
