export const DATA_LOADED = 'DATA_LOADED';
export const SELECT_PRIORITIES = 'SELECT_PRIORITIES';
export const FILTER_PRIORITIES = 'FILTER_PRIORITIES';
export const CHANGE_PRIORITY = 'CHANGE_PRIORITY';

export const MAX_PRIORITY = 1;
export const MIN_PRIORITY = 5;